#!/bin/bash
# set iptables

[ -r $INTCP/cmd/my.conf ] && . $INTCP/cmd/my.conf
iptables -t mangle -F
# 设置策略路由
ip rule add fwmark 1 table 100 
ip route add local 0.0.0.0/0 dev lo table 100

# 代理局域网设备
iptables -t mangle -N V2RAY
iptables -t mangle -A V2RAY -d 127.0.0.1/32 -j RETURN
iptables -t mangle -A V2RAY -d 224.0.0.0/4 -j RETURN 
iptables -t mangle -A V2RAY -d 255.255.255.255/32 -j RETURN 
# iptables -t mangle -A V2RAY -d 192.168.0.0/16 -p tcp -j RETURN # 直连局域网，避免 V2Ray 无法启动时无法连网关的 SSH，如果你配置的是其他网段（如 10.x.x.x 等），则修改成自己的
# iptables -t mangle -A V2RAY -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN # 直连局域网，53 端口除外（因为要使用 V2Ray 的 
# iptables -t mangle -A V2RAY -p udp -j TPROXY --on-port 5000 --tproxy-mark 1 # 给 UDP 打标记 1，转发至 12345 端口
iptables -t mangle -A V2RAY -p tcp -j TPROXY --on-port ${myport} --tproxy-mark 1 # 给 TCP 打标记 1，转发至 12345 端口
iptables -t mangle -I V2RAY -m mark --mark 0xff -j RETURN # 防止环路
iptables -t mangle -A PREROUTING -j V2RAY # 应用规则

