#!/bin/bash
cd `dirname $0`
# set iptables and start pepsal with hybla

#echo "setting iptables..."
./setipt

#echo "starting pepsal..."
#../pepsal/src/pepsal  -C $1 > ../logs/pep.txt
#../pepsal/src/pepsal  -v -C $1
if [ $# -eq 1 ];then
    ../pepsal/src/pepsal -C $1 >/dev/null 2>&1
else
    ../pepsal/src/pepsal -n -C $1 >/dev/null 2>&1
fi
