#!/bin/bash
cd `dirname $0`
# set iptables and start pepsal with hybla

[ -r ../my.conf ] && . ../my.conf

SILENT=">/dev/null 2>&1"

CCA=""
LOG=""
while getopts "vC:" opt
do
    case $opt in
        v)
        LOG="-v"
        SILENT=""
        ;;
        C)
        CCA="-C $OPTARG"
        ;;
        ?)
        echo "Unknown opt"
        exit 1;;
    esac
done

#echo "setting iptables..."
./setipt

#echo "starting pepsal..."
../pepsal${PROTOCOL}/src/pepsal -n ${PEP_TCP_NODELAY} ${CCA} ${LOG} ${SILENT}